### ISSUE TITLE
[Bug] error during build: "InsertCommand" is not exported by "node_modules/@univerjs/docs/lib/es/index.js"

### ISSUE THREAD

**Issue by mukiwu** [dream-num/univer#3544]
### 在您提交此问题之前，您是否检查了以下内容？

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

0.2.15

### 复现链接

使用 vite 在 build 檔案的時候，出現以下錯誤

```
error during build:
node_modules/@univerjs/facade/lib/es/index.js (15:9): "InsertCommand" is not exported by "node_modules/@univerjs/docs/lib/es/index.js", imported by "node_modules/@univerjs/facade/lib/es/index.js".

file: /node_modules/@univerjs/facade/lib/es/index.js:15:9

13: import { ClearRangeDataValidationCommand, AddSheetDataValidationCommand, SheetsDataValidationValidatorService, DataVa...
14: import { SetNumfmtCommand } from "@univerjs/sheets-numfmt";
15: import { filter } from "rxjs";
             ^
16: var __defProp$7 = Object.defineProperty, __getOwnPropDesc$7 = Object.getOwnPropertyDescriptor, __decorateClass$7 = /*...
17:   for (var result = kind > 1 ? void 0 : kind ? __getOwnPropDesc$7(target, key) : target, i = decorators.length - 1, d...

    at getRollupError (file:///var/www/warroom-3.0/node_modules/rollup/dist/es/shared/parseAst.js:392:41)
    at error (file:///var/www/warroom-3.0/node_modules/rollup/dist/es/shared/parseAst.js:388:42)
    at Module.error (file:///var/www/warroom-3.0/node_modules/rollup/dist/es/shared/node-entry.js:13971:16)
    at Module.traceVariable (file:///var/www/warroom-3.0/node_modules/rollup/dist/es/shared/node-entry.js:14419:29)
    at ModuleScope.findVariable (file:///var/www/warroom-3.0/node_modules/rollup/dist/es/shared/node-entry.js:12121:39)
    at ChildScope.findVariable (file:///var/www/warroom-3.0/node_modules/rollup/dist/es/shared/node-entry.js:7467:38)
    at ClassBodyScope.findVariable (file:///var/www/warroom-3.0/node_modules/rollup/dist/es/shared/node-entry.js:7467:38)
    at ChildScope.findVariable (file:///var/www/warroom-3.0/node_modules/rollup/dist/es/shared/node-entry.js:7467:38)
    at ChildScope.findVariable (file:///var/www/warroom-3.0/node_modules/rollup/dist/es/shared/node-entry.js:7467:38)
    at FunctionScope.findVariable (file:///var/www/warroom-3.0/node_modules/rollup/dist/es/shared/node-entry.js:7467:38)
    at FunctionBodyScope.findVariable (file:///var/www/warroom-3.0/node_modules/rollup/dist/es/shared/node-entry.js:7467:38)
    at MemberExpression.bind (file:///var/www/warroom-3.0/node_modules/rollup/dist/es/shared/node-entry.js:8843:49)
    at CallExpression.bind (file:///var/www/warroom-3.0/node_modules/rollup/dist/es/shared/node-entry.js:4804:28)
    at CallExpression.bind (file:///var/www/warroom-3.0/node_modules/rollup/dist/es/shared/node-entry.js:9224:15)
    at ReturnStatement.bind (file:///var/www/warroom-3.0/node_modules/rollup/dist/es/shared/node-entry.js:4808:23)
    at BlockStatement.bind (file:///var/www/warroom-3.0/node_modules/rollup/dist/es/shared/node-entry.js:4804:28)
```

### 预期行为

可以 build 成功

### 实际行为

之前使用 0.2.8 版可以正常 build，但一段時間沒有更新資料，這兩天要 build 的時候，就出現錯誤。 (已更新到 0.2.15)

### 运行环境

Chrome

**Comment by mukiwu** [comment]
用 `npm ls`  檢查後發現有一個套件沒有升級到 0.2.15，問題已解決
