### ISSUE TITLE
[Bug] Why does an error appear when I download the vue3 template and introduce univerjs-pro/facade according to the documentation tutorial?

### ISSUE THREAD

**Issue by 1316346949** [dream-num/univer#3986]
### 在您提交此问题之前，您是否检查了以下内容？

- [X] 这真的是个问题吗？
- [X] 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。

### 受影响的包和版本

"@univerjs-pro/facade": "^0.4.2",     "@univerjs/core": "0.4.1",     "@univerjs/design": "0.4.1",     "@univerjs/docs": "0.4.1",     "@univerjs/docs-ui": "0.4.1",     "@univerjs/engine-formula": "0.4.1",     "@univerjs/engine-render": "0.4.1",     "@univerjs/network": "0.4.1",     "@univerjs/rpc": "0.4.1",     "@univerjs/sheets": "0.4.1",     "@univerjs/sheets-formula": "0.4.1",     "@univerjs/sheets-formula-ui": "0.4.1",     "@univerjs/sheets-numfmt": "0.4.1",     "@univerjs/sheets-ui": "0.4.1",     "@univerjs/ui": "0.4.1",     "@univerjs/watermark": "^0.4.2",     "vue": "^3.5.8"

### 复现链接

const univer = new Univer({
    theme: defaultTheme,
    locale: LocaleType.ZH_CN,
    locales: {
      [LocaleType.ZH_CN]: zhCN,
      [LocaleType.EN_US]: enUS,
    },
  });

  const univerAPI = FUniver.newAPI(univer.__getInjector());
  const permission = univerAPI.getPermission();

### 预期行为

![image](https://github.com/user-attachments/assets/5807d2d0-f40e-443d-a215-10006b1c71a0)

### 实际行为

![Uploading image.png…]()

### 运行环境

Chrome

### 系统信息

 Cannot read properties of undefined (reading 'createInstance')
    at _a1210.getPermission (index.js:3832:27)
    at init (UniverSheet.vue:74:32)
    at UniverSheet.vue:52:3
    at runtime-core.esm-bundler.js:2762:40
    at callWithErrorHandling (runtime-core.esm-bundler.js:199:19)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:206:17)
    at hook.__weh.hook.__weh (runtime-core.esm-bundler.js:2742:19)
    at flushPostFlushCbs (runtime-core.esm-bundler.js:388:28)
    at render2 (runtime-core.esm-bundler.js:5938:7)
    at mount (runtime-core.esm-bundler.js:3887:13)

**Comment by 1316346949** [comment]
const univerAPI = FUniver.newAPI(univer);
ts类型报错：
![image](https://github.com/user-attachments/assets/f7e8636e-0b8b-42ca-97f5-b74d895b57f7)
chrome报错
index.js:3517 
 Uncaught TypeError: injector.get is not a function
    at FUniver.getDependencies (index.js:3517:21)
    at FUniver.newAPI (index.js:3529:20)
    at init (UniverSheet.vue:73:29)
    at UniverSheet.vue:52:3
    at runtime-core.esm-bundler.js:2762:40
    at callWithErrorHandling (runtime-core.esm-bundler.js:199:19)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:206:17)
    at hook.__weh.hook.__weh (runtime-core.esm-bundler.js:2742:19)
    at flushPostFlushCbs (runtime-core.esm-bundler.js:388:28)
    at render2 (runtime-core.esm-bundler.js:5938:7)

**Comment by jikkai** [comment]
You did not provide a valid minimal reproduction according to the community guidelines, so we will close this issue for now. You are welcome to reopen it at any time once you have prepared the reproduction.
